exports.RARITIES = {
	LEGENDARY: "Legendary",
	EPIC: "Epic",
	RARE: "Rare",
	COMMON: "Common"
};
exports.RARITIES_BY_INDEX = [
	this.RARITIES.LEGENDARY,
	this.RARITIES.EPIC,
	this.RARITIES.RARE,
	this.RARITIES.COMMON,
];

exports.COLLECTION = {
	ALIENS: "Aliens",
	ANGELS: "Angels",
	UNDEAD: "Undead",
	WILDLIFE: "Wildlife",
	CYBERPUNKS: "Cyberpunks",
	FASHION: "Fashion",
	HELL: "Hell",
	NINJA: "Ninja",
	PIRATES: "Pirates",
	POOL_PARTY: "Pool Party ",
	NOBLES: "Nobles",
	GLADIATORS: "Gladiators",
	PRINCESS: "Princess",
	WILD_WEST: "Wild West",
};

exports.COLLECTION_BY_INDEX = [
	"",
	this.COLLECTION.ALIENS,
	this.COLLECTION.ANGELS,
	this.COLLECTION.UNDEAD,
	this.COLLECTION.WILDLIFE,
	this.COLLECTION.CYBERPUNKS,
	this.COLLECTION.FASHION,
	this.COLLECTION.HELL,
	this.COLLECTION.NINJA,
	this.COLLECTION.PIRATES,
	this.COLLECTION.POOL_PARTY,
	this.COLLECTION.NOBLES,
	this.COLLECTION.GLADIATORS,
	this.COLLECTION.PRINCESS,
	this.COLLECTION.WILD_WEST,
];
